language: php

php:
  - 7.4snapshot

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --prefer-dist

before_script:
  - echo 'zend.assertions=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'assert.exception=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - yes | pecl install xdebug
  - echo 'zend_extension=xdebug.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - travis_retry php ocular.phar code-coverage:upload --format=php-clover coverage.xml
  - travis_retry bash <(curl -s https://codecov.io/bash)
