language: php

php:
  - 7.4snapshot

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - travis_retry php ocular.phar code-coverage:upload --format=php-clover coverage.xml
  - travis_retry bash <(curl -s https://codecov.io/bash)
